### ISSUE TITLE
Requested feature list for Nov 8th

### ISSUE THREAD

**Issue by NickolausDS** [globusonline/pilot1-tools#103]
Here's a list of changes we discussed from the last call. 

- [x] Change `pilot list` to show directories in the project's folder
- [x] For `pilot upload`, show warning when Globus connect personal is not running
    - [x] Attempt to autoactivate the endpoint when starting a transfer
- [x] After `pilot upload`, change 'success' message to tell the user they should run `pilot status` to check the status of transfer. (Currently, it implies everything succeeded and simply posts a link to the portal, which may not be the case if the files are still transferring, or are failing to start for some reason). 
- [x] For `pilot status` - get the ‘nice status’ instead of 'basic' status, which does not capture transfer errors during an active transfer, such as when GCP isn't running.
- [x] For `pilot upload —help`
	- [x] Link to docs for how to upload metadata (which fields supported, how to format etc)
- [x] `pilot describe` should show number of files if user uploads multiple files in a directory
    - [x] show each files's type in parenthesis (text/plain) when listing
    - [x] Show total number of files per-mimetype (when listing mimetypes)
    - [x] limit the number of files shown to 10

**Comment by rpwagner** [comment]
- For `list` show top level empty directories by default
- Add `list` `<dir name>` to list empty directories and datasets under `<dir name>`

**Comment by NickolausDS** [comment]
I updated the checklist above with the items you put here, and created a new issue #106 to track caching. (also #104, for migrating the nci pilot1 project)

**Comment by NickolausDS** [comment]
Everything above should be captured in #107 #108

**Comment by NickolausDS** [comment]
These features are now live in conda under version `0.4.1.dev5`.
