### ISSUE TITLE
`pilot list` on ncipilot project does not list entries

### ISSUE THREAD

**Issue by NickolausDS** [globusonline/pilot1-tools#104]
This may be due to restructuring how we built URLs for a given list of search records, so this might include a migration. I'll need to investigate.

**Comment by NickolausDS** [comment]
The problem came from the ncipilot project being old and outside of the `/projects` directory. We supported this for a while, but at same point some safety code to prevent unintentionally modifying files outside of a project prevented regular commands from working. I fixed this by mirroring it into the `/projects` directory with the name `ncipilot1-project` and migrating the search records. This allows the current ncipilot1 project files to be viewed/modified. We can discuss further action if this isn't sufficient.

**Comment by rpwagner** [comment]
Well done.
