### ISSUE TITLE
Identity and other features

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#18]
- [x] Fix delete command
    * Delete command now allows deleting by entry, or deleting the whole subject
- [x] Add '--delete-data' flag to allow deleting data in addition to search subjects/entries
- [x] Change output of field metadata in `pilot describe` to match the field order of the portal
- [x] Fix upload command re-uploading data even if the file hasn't changed
- [x] Change `pilot upload --dry-run --verbose foo bar` to format output like the describe command
- [x] Fix upload command starting on version 2
- [ ] Add `update` subcommand to update search metadata associated with the file without requiring access to the file itself. 

- [x] Add a default project configuration including:
  - [x] Search index
  - [x] default `visible_to` group
  - [x] Base endpoint and path
  - [ ] ~Default identity provider~
  - [ ] ~Include prod and test for each project~

- [x] Pull the creator identity from the logged in user based on the project IdP
  - [x] Allow to be overridden by user provided metadata
- [x] Try to determine mime type automatically, override via user metadata
- [x] Support using Globus transfer for `download` command

Later

- [x] Add multi-file handling (`pilot upload -j <metadata.json> <file1> <file2> ... <fileN> <dir>`
 - [x] May need to switch to resource descriptions to enable field metadata on a per-file basis.

**Comment by NickolausDS** [comment]
All items in this checklist have been completed.
