### ISSUE TITLE
HTTP PUT does not fully overwrite files

### ISSUE THREAD

**Issue by NickolausDS** [globusonline/pilot1-tools#35]
When doing a PUT on files using the HTTP module, if the new file is shorter than the older file, remnants of the old file will remain at the end of the new file. For example, if you did two PUTs, one after the other with the contents:

* File1: This is a big long description with lots of words
* File2: Shorter Description

The result will be: `Shorter Descriptiondescription with lots of words`

**Comment by rpwagner** [comment]
Is this only on Petrel or have you tested it on the HTTPS tutorial endpoint?

**Comment by NickolausDS** [comment]
Only Petrel so far

**Comment by rpwagner** [comment]
Try the Jupyter HTTPS endpoint and see what happens, please
```
https://app.globus.org/file-manager?origin_id=d5affa19-e218-48b8-8c39-0b1b05b9540e&origin_path=%2Frpwagner%2Fusers%2F
```

**Comment by NickolausDS** [comment]
Confirmed the same behavior on the endpoint you listed above.

**Comment by rpwagner** [comment]
Huh. Well now I'm not sure it's `pilot` or GCS. Have you tried `wget` or `curl`?

**Comment by NickolausDS** [comment]
I'm pretty sure it's GCS. You can check out the link here where I overwrote a repeating string: https://a711c.08cc.dn.glob.us/rpwagner/users/nickolaussainthe2gmmddgm4doljz/test.txt
I tested the Jupyter HTTPS endpoint using jupyter.demo.globus.org instead of the pilot client.

**Comment by rpwagner** [comment]
Can you open a ticket in the GCS HTTPS repo with a snippet of Python code to reproduce it using the Jupyter HTTPS demo endpoint?

**Comment by NickolausDS** [comment]
Sure

**Comment by rpwagner** [comment]
When you do, you can link it here and close this, since it's not on us.

**Comment by NickolausDS** [comment]
Opened and closed, that was fast. @lukaszlacinski Can you update the petrel https server?

**Comment by NickolausDS** [comment]
This has been fixed.
