### ISSUE TITLE
Project description update & project delete

### ISSUE THREAD

**Issue by rpwagner** [globusonline/pilot1-tools#41]
I'm not sure how much to support, but some changes to the project metadata should be allowed. Likewise, project delete is another challenge.

**Comment by NickolausDS** [comment]
Delete might not be too difficult from a technical perspective. Three simple steps of:

* Delete the entire project directory (delete all files)
* Delete by faceting project search records (this was a handy addition to search at some point)
* Update the project manifest. 

Updating the base path, group, or endpoint on an existing project will be a lot harder until we can "migrate" search results.
